## Advanced_CI_w4
### CH7

### 7.1 이산형 처치 메타러너

In [1]:
import pandas as pd
import numpy as np

data_biased = pd.read_csv("email_obs_data.csv")
data_rnd = pd.read_csv("email_rnd_data.csv")

print(len(data_biased), len(data_rnd))
data_rnd.head()

300000 10000

,mkt_email,next_mnth_pv,age,tenure,ammount_spent,vehicle,food,beverage,art,baby,...,electronics,sports,tools,games,industry,pc,jewel,books,music_books_movies,health
0,0,244.26,61.0,1.0,21.84,0,2,2,0,2,...,1,0,0,3,1,0,1,0,0,2
1,0,29.67,36.0,1.0,107.40,0,2,0,2,0,...,1,1,1,2,1,2,1,0,2,2
2,0,11.73,64.0,0.0,59.81,0,1,0,0,0,...,2,0,0,3,0,1,0,1,0,1
3,0,41.41,74.0,0.0,62.98,0,1,0,0,3,...,1,0,2,2,1,1,0,4,1,0
4,0,447.89,59.0,0.0,72.56,0,1,1,3,2,...,5,0,0,1,0,0,1,1,2,1

In [3]:
y = "next_mnth_pv"
T = "mkt_email"
X = list(data_rnd.drop(columns=[y, T]).columns)

train, test = data_biased, data_rnd

In [4]:
from lightgbm import LGBMRegressor

np.random.seed(123)

m0 = LGBMRegressor()
m1 = LGBMRegressor()

m0.fit(train.query(f"{T}==0")[X], train.query(f"{T}==0")[y])
m1.fit(train.query(f"{T}==1")[X], train.query(f"{T}==1")[y])

LGBMRegressor()

In [5]:
t_learner_cate_test = test.assign(
    cate = m1.predict(test[X]) - m0.predict(test[X])
)

In [ ]:
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMRegressor

# 성향점수 모델
ps_model = LogisticRegression(penalty=None)
ps_model.fit(train[X], train[T])

# 첫 번째 단계 모델
train_t0 = train.query(f"{T}==0")
train_t1 = train.query(f"{T}==1")

m0 = LGBMRegressor()
m1 = LGBMRegressor()
np.random.seed(123)

m0.fit(train_t0[X], train_t0[y],
       sample_weight=1/ps_model.predict_proba(train_t0[X])[:,0])
m1.fit(train_t1[X], train_t1[y],
       sample_weight=1/ps_model.predict_proba(train_t1[X])[:,1])

LGBMRegressor()

In [8]:
# 두 번째 단계 모델
tau_hat_0 = m1.predict(train_t0[X]) - train_t0[y]
tau_hat_1 = train_t1[y] - m0.predict(train_t1[X])

m_tau_0 = LGBMRegressor()
m_tau_1 = LGBMRegressor()

np.random.seed(123)

m_tau_0.fit(train_t0[X], tau_hat_0)
m_tau_1.fit(train_t1[X], tau_hat_1)

LGBMRegressor()

In [9]:
# CATE 추정
ps_test = ps_model.predict_proba(test[X])[:,1]

x_cate_test = test.assign(
    cate = (ps_test*m_tau_0.predict(test[X]) +
            (1-ps_test)*m_tau_1.predict(test[X])
            )
)

### 7.2 연속형 처치 메타러너

In [10]:
data_cont = pd.read_csv("discount_data.csv")
data_cont.head()

,rest_id,day,month,weekday,weekend,is_holiday,is_dec,is_nov,competitors_price,discounts,sales
0,0,2016-01-01,1,4,False,True,False,False,2.88,0,79.0
1,0,2016-01-02,1,5,True,False,False,False,2.64,0,57.0
2,0,2016-01-03,1,6,True,False,False,False,2.08,5,294.0
3,0,2016-01-04,1,0,False,False,False,False,3.37,15,676.5
4,0,2016-01-05,1,1,False,False,False,False,3.79,0,66.0

In [11]:
train = data_cont.query("day<'2018-01-01'")
test = data_cont.query("day>='2018-01-01'")

In [14]:
X = ["month", "weekday", "is_holiday", "competitors_price"]
T = "discounts"
y = "sales"

np.random.seed(123)
s_learner = LGBMRegressor()
s_learner.fit(train[X+[T]], train[y])

LGBMRegressor()

In [ ]:
t_grid = pd.DataFrame(dict(key=1, discounts=np.array([0, 10, 20, 30, 40])))

test_cf = (test
           .drop(columns=["discounts"])
           .assign(key=1)
           .merge(t_grid)
           # 확장된 데이터에서 예측
           .assign(sales_hat = lambda d: s_learner.predict(d[X+[T]]))
           )
test_cf.head(8)

,rest_id,day,month,weekday,weekend,is_holiday,is_dec,is_nov,competitors_price,sales,key,discounts,sales_hat
0,0,2018-01-01,1,0,False,True,False,False,4.92,251.5,1,0,67.957972
1,0,2018-01-01,1,0,False,True,False,False,4.92,251.5,1,10,444.245941
2,0,2018-01-01,1,0,False,True,False,False,4.92,251.5,1,20,793.045769
3,0,2018-01-01,1,0,False,True,False,False,4.92,251.5,1,30,1279.640793
4,0,2018-01-01,1,0,False,True,False,False,4.92,251.5,1,40,1512.630767
5,0,2018-01-02,1,1,False,False,False,False,3.06,541.0,1,0,65.672080
6,0,2018-01-02,1,1,False,False,False,False,3.06,541.0,1,10,495.669220
7,0,2018-01-02,1,1,False,False,False,False,3.06,541.0,1,20,1015.401471

In [18]:
from toolz import curry

@curry
def linear_effect(df, y, t): # beta
    return np.cov(df[y], df[t])[0, 1]/df[t].var()

cate = (test_cf
        .groupby(["rest_id","day"])
        .apply(linear_effect(t="discounts", y="sales_hat"))
        .rename("cate")
        )

test_s_learner_pred = test.set_index(["rest_id", "day"]).join(cate)

test_s_learner_pred.head()

C:\Users\User\AppData\Local\Temp\ipykernel_9480\3215160945.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(linear_effect(t="discounts", y="sales_hat"))

                    month  weekday  weekend  is_holiday  is_dec  is_nov  \
rest_id day
0       2018-01-01      1        0    False        True   False   False
        2018-01-02      1        1    False       False   False   False
        2018-01-03      1        2    False       False   False   False
        2018-01-04      1        3    False       False   False   False
        2018-01-05      1        4    False       False   False   False

                    competitors_price  discounts  sales       cate
rest_id day
0       2018-01-01               4.92          5  251.5  37.247404
        2018-01-02               3.06         10  541.0  40.269854
        2018-01-03               4.61         10  431.0  37.412988
        2018-01-04               4.84         20  760.0  38.436815
        2018-01-05               6.29          0   78.0  31.428603

In [ ]:
from sklearn.model_selection import cross_val_predict

X = ["month", "weekday", "is_holiday", "competitors_price"]
T = "discounts"
y = "sales"

debias_m = LGBMRegressor()
denoise_m = LGBMRegressor()

t_res = train[T] - cross_val_predict(debias_m, train[X], train[T], cv = 5) # cv = fold 개수
y_res = train[y] - cross_val_predict(denoise_m, train[X], train[y], cv = 5)

In [ ]:
import statsmodels.api as sm # statsmodels.formula.api와 차이점??

sm.OLS(y_res, t_res).fit().summary().tables[1]

"""
import statsmodels.formula.api as smf
smf.ols("y_res ~ t_res").fit() 
"""

In [21]:
y_star = y_res/t_res
w = t_res**2

cate_model = LGBMRegressor().fit(train[X], y_star, sample_weight=w)

test_s_learner_pred = test.assign(cate = cate_model.predict(test[X]))

In [22]:
np.random.seed(123)
n = 5000

x_h = np.random.randint(1, 4, n)
x_c = np.random.uniform(-1, 1, n)

t = np.random.normal(10 + 1*x_c + 3*x_c**2 + x_c**3, 0.3)
y = np.random.normal(t + x_h*t - 5*x_c - x_c**2 - x_c**3, 0.3)

df_sim = pd.DataFrame(dict(x_h=x_h, x_c=x_c, t=t, y=y))

In [23]:
debias_m = LGBMRegressor(max_depth=3)
denoise_m = LGBMRegressor(max_depth=3)

t_res = cross_val_predict(debias_m, df_sim[["x_c"]], df_sim["t"], cv=10)
y_res = cross_val_predict(denoise_m, df_sim[["x_c", "x_h"]], df_sim["y"], cv=10)

df_res = df_sim.assign(
    t_res = df_sim["t"] - t_res,
    y_res = df_sim["y"] - y_res
)

In [25]:
import statsmodels.formula.api as smf

float(smf.ols("y_res ~ t_res", data=df_res).fit().params["t_res"])

3.0452301460062934

In [27]:
df_star = df_res.assign(
    y_star = df_res["y_res"]/df_res["t_res"],
    weight = df_res["t_res"]**2,
)

for x in range(1, 4):
    cate = np.average(df_star.query(f"x_h=={x}")["y_star"], weights = df_star.query(f"x_h=={x}")["weight"])
    print(f"CATE x_h={x}", cate)

CATE x_h=1 2.019759619990067
CATE x_h=2 2.974967932350952
CATE x_h=3 3.9962382855476957